title: Tanner Steorts
description: Software Engineer at Fence Cloud. An enteprise software company that provides a cloud-based platform for the fence industry.
show_downloads: false
google_analytics: 
theme: jekyll-theme-cayman